name: "Scavene Action"
description: "Enhance your NEAR smart contract security with Scavene, the audit tool that detects vulnerabilities and ensures best practices."
author: "Ahnaf Alfariza"

inputs:
  folder_path:
    description: "Path to the folder containing Rust files to audit"
    required: false
    default: ""
  model:
    description: "Model to use for auditing (gpt-4o, gpt-3.5-turbo, or claude-3.5-sonnet)"
    required: false
  output_file:
    description: "Output file name for audit results"
    required: false
  openai_api_key:
    description: "OpenAI API key"
    required: false
  anthropic_api_key:
    description: "Anthropic API key"
    required: false
  myToken:
    description: "GitHub Token"
    required: true
  ref:
    description: "Git reference (branch, tag, or commit SHA) to checkout"
    required: false
    default: "master"

runs:
  using: "composite"
  steps:
    - name: Checkout tool
      uses: actions/checkout@v4
      with:
        repository: ahnafalfariza/scavene
        ref: ${{ inputs.ref }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: contract

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run Javascript Action
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}
        ANTHROPIC_API_KEY: ${{ inputs.anthropic_api_key }}
      with:
        folder_path: ${{ inputs.folder_path }}
        model: ${{ inputs.model }}
        output_file: ${{ inputs.output_file }}
        openai_api_key: ${{ inputs.openai_api_key }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        myToken: ${{ inputs.myToken }}
      uses: ./actions

branding:
  icon: "git-commit"
  color: blue
