name: "Node Action"
description: "Node Action for running the audit script"

inputs:
  folder_path:
    description: "Path to the folder containing Rust files to audit"
    required: false
    default: ""
  model:
    description: "Model to use for auditing (gpt-4o, gpt-3.5-turbo, or claude-3.5-sonnet)"
    required: false
  output_file:
    description: "Output file name for audit results"
    required: false
  openai_api_key:
    description: "OpenAI API key"
    required: false
  anthropic_api_key:
    description: "Anthropic API key"
    required: false
  myToken:
    description: "GitHub Token"
    required: true

runs:
  using: node20
  main: dist/index.js
