name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - "**"

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          model: "gpt-4o"
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          myToken: ${{ secrets.GITHUB_TOKEN }}
